CREATE TABLE ESTADO(
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CIDADE(
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    id_estado INTEGER NOT NULL,
    FOREIGN KEY (id_estado) REFERENCES ESTADO(ID)
);

CREATE TABLE PESSOA (
   id 		INTEGER PRIMARY KEY,
   nome 	VARCHAR(50) NOT NULL,
   email	VARCHAR(50) NOT NULL,
   cpfOuCnpj VARCHAR(50) NOT NULL,
   tipo VARCHAR(1) NOT NULL
);

CREATE TABLE ENDERECO (
    id INTEGER PRIMARY KEY,
    logradouro VARCHAR(100) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(100) NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    id_pessoa INTEGER NOT NULL,
    id_cidade INTEGER NOT NULL,
    FOREIGN KEY (id_pessoa) REFERENCES PESSOA(id),
    FOREIGN KEY (id_cidade) REFERENCES CIDADE(ID)
);

CREATE TABLE TELEFONES(
    ID INTEGER PRIMARY KEY,
    DDD VARCHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
);



CREATE TABLE PRODUTO(
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO NUMBER(10,2) NOT NULL,
    CATEGORIA VARCHAR(1) NOT NULL,
    URL_IMAGEM VARCHAR(100) NOT NULL 
);

CREATE SEQUENCE SEQ_PESSOA_ID AS INTEGER START WITH 1;
CREATE SEQUENCE SEQ_ENDERECO_ID AS INTEGER START WITH 1;
CREATE SEQUENCE SEQ_TELEFONE_ID AS INTEGER START WITH 1;
CREATE SEQUENCE SEQ_PRODUTO_ID AS INTEGER START WITH 1;

